const colors = {
  light: {
    text: '#0D1526',
    tint: '#1A5CFF',
    background: '#F4F6FB',
    foreground: '#0D1526',
    card: '#FFFFFF',
    cardForeground: '#0D1526',
    primary: '#1A5CFF',
    primaryForeground: '#FFFFFF',
    secondary: '#EEF2FF',
    secondaryForeground: '#1A2540',
    muted: '#EEF2FF',
    mutedForeground: '#6B7A99',
    accent: '#00C9A7',
    accentForeground: '#FFFFFF',
    destructive: '#EF4444',
    destructiveForeground: '#FFFFFF',
    border: '#DDE2F0',
    input: '#DDE2F0',
    success: '#10B981',
    warning: '#F59E0B',
    info: '#3B82F6',
  },
  dark: {
    text: '#E8EFFF',
    tint: '#4D8AFF',
    background: '#0D1526',
    foreground: '#E8EFFF',
    card: '#131E33',
    cardForeground: '#E8EFFF',
    primary: '#3B74FF',
    primaryForeground: '#FFFFFF',
    secondary: '#1A2B45',
    secondaryForeground: '#B0C0E8',
    muted: '#1A2B45',
    mutedForeground: '#6B7A99',
    accent: '#00C9A7',
    accentForeground: '#FFFFFF',
    destructive: '#EF4444',
    destructiveForeground: '#FFFFFF',
    border: '#1E2D45',
    input: '#1E2D45',
    success: '#10B981',
    warning: '#F59E0B',
    info: '#3B82F6',
  },
  radius: 12,
};

export default colors;
